export const elements = {
    homePage: document.getElementById('home-page'),
    quizPage: document.getElementById('quiz-page'),
    resultsPage: document.getElementById('results-page'),
    studyPage: document.getElementById('study-page'),
    quizMainTitle: document.getElementById('quiz-main-title'),
    userNameInput: document.getElementById('user-name-input'),
    categorySelect: document.getElementById('category-select'),
    difficultySelect: document.getElementById('difficulty-select'),
    numQuestionsSelect: document.getElementById('num-questions-select'),
    timePerQuestionInput: document.getElementById('time-per-question-input'),
    startQuizBtn: document.getElementById('start-quiz-btn'),
    resetGameDataBtn: document.getElementById('reset-game-data-btn'),
    currentQNumSpan: document.getElementById('current-q-num'),
    totalQNumSpan: document.getElementById('total-q-num'),
    quizProgressBar: document.getElementById('quiz-progress-bar'),
    questionText: document.getElementById('question-text'),
    answerButtonsContainer: document.getElementById('answer-buttons'),
    timeLeftSpan: document.getElementById('time-left'),
    currentScoreSpan: document.getElementById('current-score'),
    feedbackMessage: document.getElementById('feedback-message'),
    nextQuestionBtn: document.getElementById('next-question-btn'),
    loadingIndicator: document.getElementById('loading-indicator'),
    finalScoreSpan: document.getElementById('final-score'),
    correctAnswersCountSpan: document.getElementById('correct-answers-count'),
    incorrectAnswersCountSpan: document.getElementById('incorrect-answers-count'),
    unansweredQuestionsCountSpan: document.getElementById('unanswered-questions-count'),
    averageTimePerQuestionSpan: document.getElementById('average-time-per-question'),
    streakBonusScoreSpan: document.getElementById('streak-bonus-score'),
    timeBonusScoreSpan: document.getElementById('time-bonus-score'),
    incorrectAnswersReview: document.getElementById('incorrect-answers-review'),
    restartQuizBtn: document.getElementById('restart-quiz-btn'),
    shareScoreBtn: document.getElementById('share-score-btn'),
    goHomeBtn: document.getElementById('go-home-btn'),
    themeToggleCheckbox: document.getElementById('theme-toggle-checkbox'),
    muteToggleCheckbox: document.getElementById('mute-toggle-checkbox'),
    fiftyFiftyBtn: document.getElementById('fifty-fifty-btn'),
    skipQuestionBtn: document.getElementById('skip-question-btn'),
    lifelinesContainer: document.querySelector('.lifelines'),
    quizTypeBengaliRadio: document.getElementById('quiz-type-bengali'),
    quizTypeEnglishRadio: document.getElementById('quiz-type-english'),
    difficultyWrapper: document.querySelector('.difficulty-wrapper'),
    modalContainer: document.getElementById('modal-container'),
    modalTitle: document.getElementById('modal-title'),
    modalText: document.getElementById('modal-text'),
    modalConfirmBtn: document.getElementById('modal-confirm-btn'),
    modalCopyBtn: document.getElementById('modal-copy-btn'),
    modalCancelBtn: document.getElementById('modal-cancel-btn'),
    studyContent: document.getElementById('study-content'),
    studyTimer: document.getElementById('study-timer'),
    startQuizFromStudyBtn: document.getElementById('start-quiz-from-study-btn'),
    // Labels for localization
    userNameLabel: document.querySelector('label[for="user-name-input"]'),
    categoryLabel: document.querySelector('label[for="category-select"]'),
    numQuestionsLabel: document.querySelector('label[for="num-questions-select"]'),
    timePerQuestionLabel: document.querySelector('label[for="time-per-question-input"]'),
    quizTypeLabel: document.querySelector('.form-group:nth-of-type(2) > label'),
    difficultyLabel: document.querySelector('.difficulty-wrapper label'),
    sunIcon: document.getElementById('sun-icon'),
    moonIcon: document.getElementById('moon-icon'),
    volumeUpIcon: document.getElementById('volume-up-icon'),
    volumeOffIcon: document.getElementById('volume-off-icon'),
};

export const sounds = {
    correct: new Audio('correct.mp3'),
    incorrect: new Audio('incorrect.mp3'),
};

export const state = {
    studySyllabus: [],
    shuffledQuestions: [],
    currentQuestionIndex: 0,
    score: 0,
    correctCount: 0,
    incorrectCount: 0,
    unansweredCount: 0,
    incorrectAnswers: [],
    timer: null,
    timeRemaining: 0,
    timePerQuestion: 10,
    selectedNumQuestions: 5,
    timeTakenPerQuestion: [],
    streak: 0,
    fiftyFiftyUsed: false,
    skipUsed: false,
    totalTimeBonus: 0,
    totalStreakBonus: 0,
    currentQuizType: 'bengali',
    isMuted: false,
    allQuizQuestions: [],
    allVocabularyQuestions: [],
};
